id = "graphviz"
name = "Graphviz"
version = "0.1.0"
schema_version = 1
authors = ["Gabriel Silva <gabe@gabe.id>"]
description = "Graphviz support."
repository = "https://github.com/gabeidx/zed-graphviz"

[grammars.dot]
repository = "https://github.com/rydesun/tree-sitter-dot"
commit = "9ab85550c896d8b294d9b9ca1e30698736f08cea"
